name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: get-env
        run: |
          flutter_version=$( \
            cat .tool-versions \
              | grep flutter \
              | sed -E 's/.* ([0-9]+\.[0-9]+\.[0-9]+)\-.*/\1/' \
          )
          echo "FLUTTER_VERSION=$flutter_version" >> "$GITHUB_OUTPUT"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.get-env.outputs.FLUTTER_VERSION }}
          channel: "stable"
          cache: true
      - run: flutter pub get
      - run: flutter test
